# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('alias', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=8, verbose_name='性别')),
                ('email', models.EmailField(max_length=128, verbose_name='电子邮箱')),
                ('phone', models.CharField(default='', max_length=13, verbose_name='手机号码')),
                ('dept_id', models.CharField(default=0, max_length=20, verbose_name='部门编号')),
                ('job_number', models.CharField(default='', max_length=20, verbose_name='员工编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员权限')),
                ('creator', models.CharField(default='admin', max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
