# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_apptoken_department_role_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='员工编号'),
        ),
    ]
