# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-16 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180806_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppToken',
        ),
    ]
