# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-07 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='字段名')),
                ('field_key', models.CharField(max_length=50, verbose_name='字段标识')),
                ('ticket_id', models.IntegerField(verbose_name='工单id')),
                ('field_type_id', models.IntegerField(help_text='service.constant_service中定义', verbose_name='字段类型')),
                ('char_value', models.CharField(blank=True, default='', max_length=1000, verbose_name='字符串值')),
                ('int_value', models.IntegerField(blank=True, default=0, verbose_name='整型值')),
                ('float_value', models.FloatField(blank=True, default=0.0, verbose_name='浮点数')),
                ('bool_value', models.BooleanField(default=False, verbose_name='布尔值')),
                ('date_value', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='日期值')),
                ('datetime_value', models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0, 1), verbose_name='日期时间值')),
                ('time_value', models.TimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0, 1), verbose_name='时间值')),
                ('radio_value', models.CharField(blank=True, default='', max_length=50, verbose_name='radio值')),
                ('checkbox_value', models.CharField(blank=True, default='', help_text='逗号隔开多个选项', max_length=50, verbose_name='checkbox值')),
                ('select_value', models.CharField(blank=True, default='', max_length=50, verbose_name='下拉列表值')),
                ('multi_select_value', models.CharField(blank=True, default='', help_text='逗号隔开多个选项', max_length=50, verbose_name='多选下拉列表值')),
                ('text_value', models.TextField(blank=True, default='', verbose_name='文本值')),
                ('username_value', models.CharField(blank=True, default='', max_length=50, verbose_name='用户名')),
                ('multi_username_value', models.CharField(blank=True, default='', max_length=1000, verbose_name='多选用户名')),
                ('creator', models.CharField(default='admin', max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工单自定义字段',
                'verbose_name_plural': '工单自定义字段',
            },
        ),
        migrations.CreateModel(
            name='TicketFlowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(verbose_name='工单id')),
                ('transition_id', models.IntegerField(help_text='与workflow.Transition关联', verbose_name='流转id')),
                ('suggestion', models.CharField(blank=True, default='', max_length=1000, verbose_name='处理意见')),
                ('state_id', models.IntegerField(blank=True, default=0, verbose_name='当前状态id')),
                ('participant_type_id', models.IntegerField(verbose_name='处理人类型')),
                ('participant', models.CharField(blank=True, default='', max_length=50, verbose_name='处理人')),
                ('intervene_type_id', models.IntegerField(default=0, help_text='0.非人为干预的流转，1.转交操作，2.加签操作 3.加签完成', verbose_name='干预类型')),
                ('ticket_data', models.CharField(blank=True, default='', help_text='可以用于记录当前表单数据，json', max_length=10000, verbose_name='工单数据')),
                ('creator', models.CharField(default='admin', max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工单流转记录',
                'verbose_name_plural': '工单流转记录',
            },
        ),
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='工单的标题', max_length=128, verbose_name='标题')),
                ('workflow_id', models.IntegerField(help_text='与 workflow.Workflow 流程关联', verbose_name='关联的流程id')),
                ('sn', models.CharField(help_text='工单的流水号', max_length=25, verbose_name='流水号')),
                ('state_id', models.IntegerField(help_text='与 workflow.State 关联', verbose_name='当前状态')),
                ('parent_ticket_id', models.IntegerField(default=0, help_text='与 ticket.TicketRecord 关联', verbose_name='父工单id')),
                ('parent_ticket_state_id', models.IntegerField(default=0, help_text='与workflow.State关联，子工单是关联到父工单的某个状态下的。', verbose_name='对应父工单状态id')),
                ('participant', models.CharField(blank=True, default='', help_text='可以为空(无处理人的状况比如结束状态), username\\多个username(以,隔开)\\部门id\\角色id\\脚本文件名等', max_length=128, verbose_name='当前处理人')),
                ('participant_type_id', models.IntegerField(default=0, help_text='0.无处理人,1.个人,2.多人,3.部门,4.角色', verbose_name='当前处理人类型')),
                ('relation', models.CharField(blank=True, default='', help_text='工单流转过程中将保存所有相关的人(包括创建人、曾经的待处理人)，用于查询', max_length=1024, verbose_name='工单关联人')),
                ('in_add_node', models.BooleanField(default=False, help_text='是否处于加签状态中', verbose_name='加签状态中')),
                ('add_node_man', models.CharField(blank=True, default='', help_text='加签操作的人，工单当前处理人处理完成后会回到该处理人，当处于加签状态下才有效', max_length=128, verbose_name='加签人')),
                ('creator', models.CharField(default='admin', max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工单记录',
                'verbose_name_plural': '工单记录',
            },
        ),
    ]
