"""
Django settings for yuanqu2 project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
# -*-coding:utf-8-*-

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xls=amkdx!gm3ti$&taf8ql#lxk3-stv5t%c8y@nc^hwbw=17g'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True  # 部署到服务器要改为False

ALLOWED_HOSTS = ['112.35.64.111', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend.account',
    'backend.ticket',
    'backend.workflow',
]

AUTH_USER_MODEL = 'account.User'

MIDDLEWARE = [
    'service.common.crsf_service.DisableCSRF',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 暂时取消csrf检验
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yuanqu2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yuanqu2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yuanqu',  # 部署到服务器数据库名称要改
        'USER': 'root',  # 部署到服务器用户名要改
        'PASSWORD': '!QAZ2wsx',  # 部署到服务器密码要改
        'HOST': 'localhost',  # 部署到服务器要改为127.0.0.1
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, "common_static"),)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 上传文件夹
MEDIA_URL = '/media/'

# 邮箱代理设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.exmail.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'czj@x-zj.cn'
EMAIL_HOST_PASSWORD = 'uG8NTVAUE6u3N3wQ'
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = '园区资源管理系统<czj@x-zj.cn>'

USERS_VERIFY_EMAIL = False

# 默认登陆位置
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

# celery 配置
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

# 日志输出
# LOGGING = {
#         'version': 1,
#         'disable_existing_loggers': False,
#         'filters': {
#             'require_debug_true': {
#                 '()': 'django.utils.log.RequireDebugTrue',
#             },
#         },
#         'formatters': {
#             'standard': {
#                 'format': '%(asctime)s %(pathname)s process-%(process)d thread-%(thread)d %(lineno)d '
#                           '[%(levelname)s]: %(message)s',
#             },
#         },
#         'handlers': {
#             'file_handler': {
#                 'level': 'DEBUG',
#                 'class': 'logging.FileHandler',
#                 'filename': 'D:/arun.log',
#                 'formatter': 'standard'
#             },
#             'console': {
#                 'level': 'DEBUG',
#                 'filters': ['require_debug_true'],
#                 'class': 'logging.StreamHandler',
#                 'formatter': 'standard'
#             },
#         },
#         'loggers': {
#             'django': {
#                 'handlers': ['file_handler'],
#                 'propagate': True,
#                 'level': 'INFO',
#                         },
#             'django.db.backends': {
#                 'handlers': ['console'],
#                 'propagate': True,
#                 'level': 'INFO',
#             }
#         }
#     }
