# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='1990-01-01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='南方基地', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='网管支撑中心', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='job_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='第一次登陆', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='team_belong',
            field=models.CharField(default='监控分析室', max_length=20),
        ),
    ]
